### ISSUE TITLE
Integration?

### ISSUE THREAD

**Issue by ianhbell** [WolfgangErb/LC2Ditp#1]
This library is very useful to understand what is going on with these mysterious Padua points.  Any chance of also adding the routines for numerical integration?  I can't wrap my head around the literature on how to get that to work given Padua points.

**Comment by WolfgangErb** [comment]
Hi Ian,
yeah, thats a good point. I'll add a small script for the numerical integration on these points. 
Best,
Wolfgang

**Comment by WolfgangErb** [comment]
There is now a small script (LC2Dquad.m) for Clenshaw-Curtis quadrature on the Lissajous-Chebyshev nodes.

Best,
Wolfgang

**Comment by ianhbell** [comment]
Ah, turns out it is so much easier than I had expected.  Thank you very much for putting together the example.
